---
- name: Copy .osx dotfile
  copy:
    src: files/.osx
    dest: "~/.osx"
    owner: foo
    group: foo
    mode: "0644"
  become: false
- name: Run .osx dotfiles.
  command: "~/.osx"
  become: true
  changed_when: false
